export enum Routes {
    Home = 'Home',
    Study = 'Study',
    WindesheimTechRadar = 'Windesheim Tech Radar',
    WindesheimTechRadarContent = 'Windesheim Tech Radar Content',
    Settings = 'Settings',
    LoadingScreen = 'Loading screen',
    TestSettings = 'TestSettings',
    Usecase = 'Usecase',
    CaseStudyInfo = 'CaseStudyInfo',
    Stage = 'Stage',
    CourseFinished = 'CourseFinished',
    StageOverview = 'StageOverview',
    Courses = 'Courses',
}
