export enum Routes {
    Home = 'Home',
    Study = 'Study',
    WindesheimTechRadar = 'Windesheim Tech Radar',
    ScansOverview = 'Scansoverview',
    InformationPage = 'InformationPage',
    WindesheimTechRadarContent = 'Windesheim Tech Radar Content',
    Settings = 'Settings',
    LoadingScreen = 'Loading screen',
    Usecase = 'Usecase',
    CaseStudyInfo = 'CaseStudyInfo',
    CourseStage = 'Stage',
    CourseFinished = 'CourseFinished',
    StageOverview = 'StageOverview',
    Courses = 'Courses',
    EditBackgroundInformation = 'EditBackgroundInformation',
    FirstTimeUser = 'FirstTimeUser',
    PromptLibrary = 'PromptLibrary',
    PromptView = 'PromptView',
    Articles = 'Articles',
    Quizzes = 'Quizzes',
    Prompts = 'Prompts',
    MockTutorial = 'MockTutorial',
    PodcastsEpisodePage = 'PodcastsEpisodePage',
    QuestionPage = 'QuestionPage',
    Results = 'Results',
    ChooseCategories = 'ChooseCategories',
    Scans = 'Scans',
    ChatbotScreen = 'ChatbotScreen',
}

export const DefaultRoute = Routes.Home;
