export enum Routes {
    Home = 'Home',
    Study = 'Study',
    WindesheimTechRadar = 'Windesheim Tech Radar',
    WindesheimTechRadarContent = 'Windesheim Tech Radar Content',
    Settings = 'Settings',
    LoadingScreen = 'Loading screen',
    Usecase = 'Usecase',
    CaseStudyInfo = 'CaseStudyInfo',
    CourseStage = 'Stage',
    CourseFinished = 'CourseFinished',
    StageOverview = 'StageOverview',
    Courses = 'Courses',
    EditBackgroundInformation = 'EditBackgroundInformation',
    FirstTimeUser = 'FirstTimeUser',
    PromptLibrary = 'PromptLibrary',
    PromptView = 'PromptView',
    Articles = 'Articles',
    Quizzes = 'Quizzes',
    Prompts = 'Prompts',
    MockTutorial = 'MockTutorial',
    PodcastsEpisodePage = 'PodcastsEpisodePage',
}

export const DefaultRoute = Routes.Home;
